### ISSUE TITLE
Slack && Trello Links not working 

### ISSUE THREAD

**Issue by SIMAKK** [theleadio/coronatracker#32]
The links in the readme for Slack and Trello are not working 

![image](https://user-images.githubusercontent.com/4772111/76014906-14761b00-5f23-11ea-960f-43dffdbfa539.png)
![image](https://user-images.githubusercontent.com/4772111/76014930-2061dd00-5f23-11ea-90bd-f43e262ca70f.png)

**Comment by samueljklee** [comment]
Updated the invite. Closing this issue.
