### ISSUE TITLE
Add India's Database

### ISSUE THREAD

**Issue by Siddhant-K-code** [theleadio/coronatracker#55]

**Comment by samueljklee** [comment]
Hello @Siddhant-K-code, 

Thanks for raising this issue.
Do you mean adding India's news sources? If so, do you know any reliable local news sources?

Sam

**Comment by Siddhant-K-code** [comment]
It is by HEALTH MINISTRY OF INDIA : https://www.mohfw.gov.in/

**Comment by samueljklee** [comment]
Thanks! We currently have India in our database as well. I have also just merged Tamil and Hindi's news sites. Should be in the [web](coronatracker.com) soon
